// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllToken(ctx context.Context, arg DeleteAllTokenParams) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteTransaction(ctx context.Context, id uuid.UUID) error
	GetCategories(ctx context.Context) ([]Category, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetHashTokenForUser(ctx context.Context, arg GetHashTokenForUserParams) (GetHashTokenForUserRow, error)
	GetTotalExpenses(ctx context.Context) (int64, error)
	GetTotalIncome(ctx context.Context) (int64, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (GetTransactionRow, error)
	GetTransactions(ctx context.Context) ([]GetTransactionsRow, error)
	GetTransactionsByType(ctx context.Context, arg GetTransactionsByTypeParams) ([]GetTransactionsByTypeRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertCategory(ctx context.Context, arg InsertCategoryParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
